#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ "$#" -lt 4444 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
SCP_OPTIONS="-i $PATH_TO_SSH_KEY -o StrictHostKeyChecking=no"

scp "$SCP_OPTIONS" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/ 
