#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
sudo apt-get -y update
sudo apt-get -y install haproxy

# Edit the HAProxy configuration file

server_config="
frontend dtikoli-frontend
        bind *:80
        mode http
        default_backend dtikoli-backend
backend dtikoli-backend
        balance roundrobin
        server 251357-web-01 54.173.130.243:80 check
        server 251357-web-02 54.165.89.101:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
