#!/usr/bin/env bash
# This script configures Nginx to run as the 'nginx' user on port 8080.

# Modify Nginx's configuration file to change the user to 'nginx'.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change the default port from 80 to 8080 in the site configuration.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set more restrictive permissions on the Nginx configuration file.
chmod 644 /etc/nginx/nginx.conf

# Stop any running Apache processes.
pkill apache2

# Start Nginx as the 'nginx' user.
sudo -u nginx service nginx start
